apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap  
  namespace: {{ .Values.app.namespace }}
data:
  LOG_LEVEL: {{ .Values.configmap.data.LOG_LEVEL | quote }}
  ROOT_USER: {{ .Values.mongodb.auth.rootUser | quote }}
  DATABASE: {{ .Values.mongodb.auth.database | quote }}