controller:
  metrics:
    enabled: true
    serviceMonitor:
      additionalLabels:
        release: "kube-prometheus-stack"
      enabled: true
  extraArgs:
    enable-ssl-passthrough: "true"
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
  ingressClass: nginx
  resources:
    requests:
      cpu: 250m
      memory: 512Mi