# Elasticsearch values
elasticsearch:
  replicas: 2
  minimumMasterNodes: 1
  persistence:
    enabled: true
    labels:
      # Add default labels for the volumeClaimTemplate of the StatefulSet
      enabled: true
  
# Kibana values
kibana:
  ingress:
    enabled: true
    className: "nginx"
    pathtype: ImplementationSpecific
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: poster-downloader.ddns.net
        paths:
          - path: /kibana
    tls:
      - hosts:
          - poster-downloader.ddns.net
        secretName: source-tls          

# Fluent-bit values
fluent-bit:
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/poster-downloader*.log
          Tag poster-downloader.*
          Parser regex_parser
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On
          Refresh_Interval 10      

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name parser
          Match poster-downloader.*
          Key_Name log
          Parser json_parser
          Reserve_Data On
          Reserve_Time On

      [FILTER]
          Name parser
          Match poster-downloader.*
          Key_Name log
          Parser regex_parser
          Reserve_Data On
          Reserve_Time On

      [FILTER]
          Name kubernetes
          Match poster-downloader.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
        Name es
        Match poster-downloader.*
        Host elasticsearch-master
        Logstash_Format On
        Logstash_Prefix poster-downloader-logs
        Retry_Limit False

      [OUTPUT]
        Name stdout
        Match *

    customParsers: |
      [PARSER]
          Name json_parser
          Time_Keep On
          Format json
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
      
      [PARSER]
          Name regex_parser
          Format regex
          Regex ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),\d{3} - (?<level>\w+) - (?<message>.*)$
          Time_Key time
          Time_Format %Y-%m-%d %H:%M:%S
          Time_Keep On