apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  
  sources:
    - chart: kube-prometheus-stack
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 56.6.2
      helm:
        valueFiles:
          - $values/cluster-resources/kube-prometheus-stack-values.yaml
    - repoURL: 'https://github.com/AmirKatorza/develeap-portfolio-poster-downloader-gitops.git'
      targetRevision: efk
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true