apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 3000
  selector:
    app: {{ .Values.app.name }}
  type: {{ if .Values.ingress.enabled }}ClusterIP{{ else }}LoadBalancer{{ end }}