# Elasticsearch values
elasticsearch:
  global:
    elasticsearch:
      service:
        name: elasticsearch
        ports:
          restAPI: 9200
    kibanaEnabled: true
  
  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

  sysctlImage:
    ## Enable kernel settings modifier image - not available in GKE Autopilot
    ## See https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html
    enabled: true

  # Kibana values (subchart)
  # kibana:
  #   ingress:
  #     enabled: true
  #     hostname: poster-downloader.ddns.net
  #     path: /kibana
  #     # annotations:
  #     #   cert-manager.io/cluster-issuer: "letsencrypt"
  #     tls: true
  #     ingressClassName: "nginx"
  #   persistence:
  #     enabled: true
  #     size: 5Gi
  #   service:
  #     port:
  #       http: 5601
  kibana:
    elasticsearch:
      hosts:
        - '{{ include "elasticsearch.service.name" . }}'
      port: '{{ include "elasticsearch.service.ports.restAPI" . }}'


# Fluent-bit values
fluent-bit:
  luaScripts:
    setIndex.lua: |
      function set_index(tag, timestamp, record)
          index = "tmdb-"
          if record["kubernetes"] ~= nil then
              if record["kubernetes"]["namespace_name"] ~= nil then
                  if record["kubernetes"]["container_name"] ~= nil then
                      record["es_index"] = index
                          .. record["kubernetes"]["namespace_name"]
                          .. "-"
                          .. record["kubernetes"]["container_name"]
                      return 1, timestamp, record
                  end
                  record["es_index"] = index
                      .. record["kubernetes"]["namespace_name"]
                  return 1, timestamp, record
              end
          end
          return 1, timestamp, record
      end
  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*poster*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On

      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On

      [FILTER]
          Name lua
          Match kube.*
          script /fluent-bit/scripts/setIndex.lua
          call set_index

    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Type  _doc
          Host efk-stack-elasticsearch
          Port 9200
          Logstash_Format On
          Logstash_Prefix poster
          Retry_Limit False
          Suppress_Type_Name On

      [OUTPUT]
          Name es
          Match host.*
          Type  _doc
          Host efk-stack-elasticsearch
          Port 9200                   
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          Suppress_Type_Name On
    
    customParsers: |
      [PARSER]
          Name json_parser
          Format json
          Time_Keep Off
          Time_Key time
          Time_Format %Y-%m-%dT%H:%M:%S.%NZ
      
      [PARSER]
          Name flask_parser
          Format regex
          Regex ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),\d{3} - (?<level>\w+) - (?<message>.*)$
          Time_Key time
          Time_Format %Y-%m-%d %H:%M:%S
          Time_Keep On