apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: source-tls
  namespace: cert-manager
spec:
  # Secret name to create, where the private key and certificate should be stored.
  secretName: source-tls
  # What Issuer to use for getting the certificate.
  issuerRef:
    name: letsencrypt-nginx
    kind: Issuer
    group: cert-manager.io
  # Common name to be used on the Certificate.
  commonName: "poster-downloader.ddns.net"
  dnsNames:
    - "poster-downloader.ddns.net"  
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,argocd,poster-downloader,efk,monitoring"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,argocd,poster-downloader,efk,monitoring" # Control auto-reflection namespaces