apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: source-tls
  namespace: cert-manager
spec:
  secretName: source-tls
  commonName: poster-downloader.ddns.net 
  dnsNames:
    - poster-downloader.ddns.net 
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,argocd,poster-downloader,efk"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,argocd,poster-downloader,efk" # Control auto-reflection namespaces