apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
{{ if .Values.Issuer.staging }}
    # The ACME server URL (staging)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
{{ else }}
    # The ACME server URL (production)
    server: https://acme-v02.api.letsencrypt.org/directory
{{ end }}
    # Email address used for ACME registration
    email: amir.katorza@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx