app:
  name: poster-downloader
  namespace: poster-downloader
  replicaCount: 1
  image:
    repository: 644435390668.dkr.ecr.us-east-1.amazonaws.com/amirk-poster-downloader
    tag: "2.1.9"
  port: 5000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
service:
  port: 80
ingress:
  enabled: true # Set to false if you don't want to use Ingress  
  ingressControllerNamespace: ingress
  ingressClassName: nginx
  hostName: "poster-downloader.ddns.net"
  tls:
    enabled: true # Enable TLS for HTTPS    
    secretName: source-tls
configmap:
  data:
    LOG_LEVEL: "INFO"
mongodb:
  architecture: replicaset
  replicaCount: 3
  systemLogVerbosity: 3
  persistence:
    enabled: true
  auth:
    enabled: true
    existingSecret: mongodb-credentials
    rootUser: root
    username: user
    database: "movies"
